apiVersion: v1
kind: Service
metadata:
  name: nats-public
spec:
  type: NodePort
  ports:
    - port: 4222     
      name: nats-default
    - port: 443
      name: nats-websocket
  selector:
    app.kubernetes.io/name: nats
